### ISSUE TITLE
Error on Accompaniment and Vocal separation Tab

### ISSUE THREAD

**Issue by FarshadGrayson** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1218]
Every time i try to use it , i get the same error , and no , my file doesn't have spaces or underlines in it's name .

Traceback (most recent call last):
  File "D:\RVC0813Nvidia\infer-web.py", line 345, in uvr
    pre_fun = func(
  File "D:\RVC0813Nvidia\infer_uvr5.py", line 40, in __init__
    model = model.half().to(device)
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\RVC0813Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by RVC-Boss** [comment]
what's your GPU?

**Comment by FarshadGrayson** [comment]
> what's your GPU?

Nvidia RTX 3070 Ti

**Comment by FarshadGrayson** [comment]
no one can help me ???? i can't create datasets without this .

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. 

The GPU detection logic has been fixed and is now working properly.
