### ISSUE TITLE
 Warning: CUDA warning: misaligned address (function destroyEvent)

### ISSUE THREAD

**Issue by JackVinati** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1635]
I have a 4090 and it never happened before. but since last night, every time i start a training after a random number of Epochs it shows this error: 
ps I ve never had issues with with tensorflow 2.10 + cu118
```
2023-12-19 15:04:50 | INFO | __main__ | Use gpus: 0
2023-12-19 15:04:50 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "onlyyy" -sr 40k -f0 1 -bs 40 -g 0 -te 1000 -se 50 -pg assets/pretrained_v2/f0G40k.pth -pd assets/pretrained_v2/f0D40k.pth -l 0 -c 0 -sw 1 -v v2
INFO:onlyyy:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs\\onlyyy/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 40, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\onlyyy', 'experiment_dir': './logs\\onlyyy', 'save_every_epoch': 50, 'name': 'onlyyy', 'total_epoch': 1000, 'pretrainG': 'assets/pretrained_v2/f0G40k.pth', 'pretrainD': 'assets/pretrained_v2/f0D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
INFO:onlyyy:loaded pretrained assets/pretrained_v2/f0G40k.pth
INFO:onlyyy:<All keys matched successfully>
INFO:onlyyy:loaded pretrained assets/pretrained_v2/f0D40k.pth
INFO:onlyyy:<All keys matched successfully>
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
C:\RVC1006Nvidia\runtime\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:337.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:onlyyy:Train Epoch: 1 [0%]
INFO:onlyyy:[0, 0.0001]
INFO:onlyyy:loss_disc=4.082, loss_gen=2.891, loss_fm=15.638,loss_mel=23.463, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: C:\RVC1006Nvidia\runtime\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:onlyyy:====> Epoch: 1 [2023-12-19 15:05:09] | (0:00:07.118238)
INFO:onlyyy:====> Epoch: 2 [2023-12-19 15:05:12] | (0:00:03.499134)
INFO:onlyyy:====> Epoch: 3 [2023-12-19 15:05:16] | (0:00:03.404062)
INFO:onlyyy:====> Epoch: 4 [2023-12-19 15:05:19] | (0:00:03.497530)
INFO:onlyyy:====> Epoch: 5 [2023-12-19 15:05:23] | (0:00:03.634499)
INFO:onlyyy:====> Epoch: 6 [2023-12-19 15:05:27] | (0:00:03.749248)
INFO:onlyyy:====> Epoch: 7 [2023-12-19 15:05:30] | (0:00:03.551588)
INFO:onlyyy:====> Epoch: 8 [2023-12-19 15:05:34] | (0:00:03.479180)
INFO:onlyyy:====> Epoch: 9 [2023-12-19 15:05:37] | (0:00:03.627706)
INFO:onlyyy:====> Epoch: 10 [2023-12-19 15:05:41] | (0:00:03.556861)
INFO:onlyyy:====> Epoch: 11 [2023-12-19 15:05:45] | (0:00:03.641620)
INFO:onlyyy:====> Epoch: 12 [2023-12-19 15:05:48] | (0:00:03.577293)
INFO:onlyyy:====> Epoch: 13 [2023-12-19 15:05:52] | (0:00:03.643528)
INFO:onlyyy:====> Epoch: 14 [2023-12-19 15:05:55] | (0:00:03.636217)
INFO:onlyyy:====> Epoch: 15 [2023-12-19 15:05:59] | (0:00:03.613796)
INFO:onlyyy:====> Epoch: 16 [2023-12-19 15:06:03] | (0:00:03.523447)
INFO:onlyyy:====> Epoch: 17 [2023-12-19 15:06:06] | (0:00:03.558352)
INFO:onlyyy:====> Epoch: 18 [2023-12-19 15:06:10] | (0:00:03.733018)
INFO:onlyyy:====> Epoch: 19 [2023-12-19 15:06:13] | (0:00:03.526152)
INFO:onlyyy:====> Epoch: 20 [2023-12-19 15:06:17] | (0:00:03.505241)
INFO:onlyyy:====> Epoch: 21 [2023-12-19 15:06:21] | (0:00:03.628531)
INFO:onlyyy:====> Epoch: 22 [2023-12-19 15:06:24] | (0:00:03.594740)
INFO:onlyyy:====> Epoch: 23 [2023-12-19 15:06:28] | (0:00:03.500952)
INFO:onlyyy:====> Epoch: 24 [2023-12-19 15:06:31] | (0:00:03.548547)
INFO:onlyyy:====> Epoch: 25 [2023-12-19 15:06:35] | (0:00:03.518476)
INFO:onlyyy:====> Epoch: 26 [2023-12-19 15:06:38] | (0:00:03.683007)
INFO:onlyyy:====> Epoch: 27 [2023-12-19 15:06:42] | (0:00:03.656585)
INFO:onlyyy:====> Epoch: 28 [2023-12-19 15:06:46] | (0:00:03.537513)
INFO:onlyyy:Train Epoch: 29 [57%]
INFO:onlyyy:[200, 9.965058998565574e-05]
INFO:onlyyy:loss_disc=3.969, loss_gen=3.065, loss_fm=14.320,loss_mel=19.117, loss_kl=1.405
INFO:onlyyy:====> Epoch: 29 [2023-12-19 15:06:49] | (0:00:03.815573)
INFO:onlyyy:====> Epoch: 30 [2023-12-19 15:06:53] | (0:00:03.671933)
INFO:onlyyy:====> Epoch: 31 [2023-12-19 15:06:57] | (0:00:03.640256)
INFO:onlyyy:====> Epoch: 32 [2023-12-19 15:07:01] | (0:00:03.787953)
INFO:onlyyy:====> Epoch: 33 [2023-12-19 15:07:04] | (0:00:03.628818)
INFO:onlyyy:====> Epoch: 34 [2023-12-19 15:07:08] | (0:00:03.617073)
INFO:onlyyy:====> Epoch: 35 [2023-12-19 15:07:11] | (0:00:03.636687)
INFO:onlyyy:====> Epoch: 36 [2023-12-19 15:07:15] | (0:00:03.604387)
INFO:onlyyy:====> Epoch: 37 [2023-12-19 15:07:19] | (0:00:03.596382)
INFO:onlyyy:====> Epoch: 38 [2023-12-19 15:07:22] | (0:00:03.584649)
INFO:onlyyy:====> Epoch: 39 [2023-12-19 15:07:26] | (0:00:03.694741)
INFO:onlyyy:====> Epoch: 40 [2023-12-19 15:07:30] | (0:00:03.642935)
INFO:onlyyy:====> Epoch: 41 [2023-12-19 15:07:33] | (0:00:03.631553)
INFO:onlyyy:====> Epoch: 42 [2023-12-19 15:07:37] | (0:00:03.493576)
INFO:onlyyy:====> Epoch: 43 [2023-12-19 15:07:40] | (0:00:03.454305)
INFO:onlyyy:====> Epoch: 44 [2023-12-19 15:07:44] | (0:00:03.467241)
INFO:onlyyy:====> Epoch: 45 [2023-12-19 15:07:47] | (0:00:03.582940)
INFO:onlyyy:====> Epoch: 46 [2023-12-19 15:07:51] | (0:00:03.631448)
INFO:onlyyy:====> Epoch: 47 [2023-12-19 15:07:54] | (0:00:03.538454)
INFO:onlyyy:====> Epoch: 48 [2023-12-19 15:07:58] | (0:00:03.572288)
INFO:onlyyy:====> Epoch: 49 [2023-12-19 15:08:02] | (0:00:03.589449)
INFO:onlyyy:Saving model and optimizer state at epoch 50 to ./logs\onlyyy\G_350.pth
INFO:onlyyy:Saving model and optimizer state at epoch 50 to ./logs\onlyyy\D_350.pth
INFO:onlyyy:saving ckpt onlyyy_e50:Success.
INFO:onlyyy:====> Epoch: 50 [2023-12-19 15:08:06] | (0:00:04.709741)
INFO:onlyyy:====> Epoch: 51 [2023-12-19 15:08:10] | (0:00:03.525619)
INFO:onlyyy:====> Epoch: 52 [2023-12-19 15:08:13] | (0:00:03.559657)
INFO:onlyyy:====> Epoch: 53 [2023-12-19 15:08:17] | (0:00:03.576695)
INFO:onlyyy:====> Epoch: 54 [2023-12-19 15:08:21] | (0:00:03.573354)
INFO:onlyyy:====> Epoch: 55 [2023-12-19 15:08:24] | (0:00:03.716599)
INFO:onlyyy:====> Epoch: 56 [2023-12-19 15:08:28] | (0:00:03.497962)

[W CUDAGuardImpl.h:124] Warning: CUDA warning: misaligned address (function destroyEvent)
```

**Comment by JackVinati** [comment]
I've found the solution: it simply was the Nvidia driver. I just simply do a clean reinstall of it and now it works fine
