### ISSUE TITLE
Attribute Error: 'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by SilverFox12-afk** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2182]
To create a public link, set `share=True` in `launch()`.
loading weights/Nanami_e600_s2400.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\infer-web.py", line 316, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\vc_infer_pipeline.py", line 564, in pipeline
    self.vc(
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\vc_infer_pipeline.py", line 450, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Users\Desktop\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

I need help ;-;)

**Comment by SilverFox12-afk** [comment]
![Capture](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/174899382/eae0e8ab-29b9-4587-aff5-ebc35651e0af)
Ev
![Capture1](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/174899382/2a5dd955-b67d-40ed-a82b-1159cd221aaf)

**Comment by RAIACAD0564** [comment]
I was trying to figure out this issue myself and what worked for me was downgrading the av package. Hope it works for everyone else too.

`pip install --force-reinstall -v "av==11.0.0"`

**Comment by zeki0485** [comment]
doen't work. any other solution?

**Comment by Lucalme** [comment]
> doen't work. any other solution?

go to `infer\lib\audio.py`

-> Line 61, replace 
`open(file, "r") as f:`
with:
`open(file, "rb") as f:`

Hope that does it 👍

**Comment by mi-ye** [comment]
It seems that the issue is with the Gradio library. To update the library, run the following command:

pip install --upgrade gradio
Since the new version of Gradio has deprecated concurrency_count, you need to use the new method for setting concurrency limits.

Solution
Remove the concurrency_count parameter: Use Ctrl+F to find where the error is occurring in the code, and replace it with the following:
if config.iscolab:
    app.queue(max_size=1022).launch(max_threads=511)
else:
    app.queue(max_size=1022).launch(
        server_name="0.0.0.0",
        inbrowser=not config.noautoopen,
        server_port=config.listen_port,
        quiet=True,
    )
After making these changes, run the script again, and it should work.

**Comment by RitterKW** [comment]
pip install gradio==3.48.0
