### ISSUE TITLE
'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by jsoncode** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2413]
按照github readme操作之后，报错如下：

环境说明：
系统：win11
cuda版本：12.4
显卡：nvdia 4090 24G

```
2024-12-16 20:49:48 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 188, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\pipeline.py", line 354, in pipeline
    pitch, pitchf = self.get_f0(
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\pipeline.py", line 154, in get_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rmvpe.py", line 605, in infer_from_audio
    hidden = self.mel2hidden(mel)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rmvpe.py", line 584, in mel2hidden
    hidden = self.model(mel)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rmvpe.py", line 410, in forward
    x = self.fc(x)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rmvpe.py", line 174, in forward
    return self.gru(x)[0]
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\rnn.py", line 1392, in forward
    result = _VF.gru(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Traceback (most recent call last):
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\code\open\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```

**Comment by BeHappy0o0o0o0** [comment]
一样的问题，在macos ubuntu上都试了下，都是这个错误，不知道和什么相关

**Comment by aigc4o** [comment]
同样的问题，请问楼上解决了吗

**Comment by duanxiaosheng** [comment]
我也是这个问题

**Comment by aigc4o** [comment]
这软件我在服务器上尝试装了一周了，各种python、cuda环境都试了，各种报错不能用。

**Comment by toanNg3000** [comment]
Here is how I resolved the error on my computer:

1. Install a lower CUDA version of pytorch with `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
2. . Download "hubert_base.pt", "rmvpe.onnx", "rmvpe.pt" and put them in **assets/rmvpe**

My PC specs: CPU: Intel, GPU: RTX 4060Ti, OS: Win 11
