### ISSUE TITLE
I have no clue

### ISSUE THREAD

**Issue by kilegence** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2461]
What can I do to fix this

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. 

The GPU detection logic has been fixed and is now working properly.
