### ISSUE TITLE
Compatible with RTX 50

### ISSUE THREAD

**Issue by kimutaku76** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2486]
I tried to get an RTX 5090 and continue RVC work, but 
It seems that there is a conflict because sm_120 is not supported.

When running RVC, the gpu output is true, but voice synthesis fails and stops in pause.

E:\RVC1006Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
E:\RVC1006Nvidia\runtime\lib\site-packages\torch\cuda\__init__.py:173: UserWarning:
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2025-02-13 17:42:56 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 5090
is_half:True, device:cuda:0

I tried to somehow make it compatible with pytorch, but
I've spent over 40 hours trying to solve it on my own, but I can't solve it because I'm not an expert.

Can you please upgrade the version?

**Comment by syd2333** [comment]
I encountered and solved a similar issue. While my solution was for a different AI voice project, the underlying CUDA compatibility problem is the same :

https://github.com/RVC-Boss/GPT-SoVITS/issues/2026

**Comment by kimutaku76** [comment]
Thank you.
First, let's implement it according to your suggestion. :)

**Comment by jmeboypc** [comment]
Will RVC be updated once the latest PyTorch version releases on Windows?

**Comment by DEUPLECT** [comment]
Did it fix your problem as suggested by @syd2333 ?

**Comment by dirtmonster1337** [comment]
running into same problems with sm_120 did @syd2333 work for RVC project?

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this issue has already been resolved. The GPU detection logic has been fixed and is now working properly. You can install it using the cu128 setup.
