### ISSUE TITLE
这个要如何解决

### ISSUE THREAD

**Issue by zfuling** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2518]
Input device: 1:耳机 (Redmi Buds 6S) (MME)
Output device: 15:Voicemeeter Input (VB-Audio Voi (MME)
cuda_is_available: True
Traceback (most recent call last):
  File "E:\RVC1006Nvidia\RVC1006Nvidia\tools\rvc_for_realtime.py", line 106, in __init__
    hubert_model = hubert_model.half()
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this issue has already been resolved. The GPU detection logic has been fixed and is now working properly. You can install it using the cu128 setup.

**Comment by RVC-Boss** [comment]
更新到最新版本试试
