### ISSUE TITLE
5090D显卡已经配置好环境，但是打开应用后提示兼容性问题

### ISSUE THREAD

**Issue by Amoyp** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2558]
提示信息如下：
D:\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\cuda\__init__.py:173: UserWarning:
NVIDIA GeForce RTX 5090 D with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5090 D GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

环境配置信息：
>>> print(torch.__version__)  # 输出PyTorch版本
2.7.0.dev20250312+cu128
>>> print(torch.cuda.is_available())  # 检查CUDA是否可用
True
>>> print(torch.cuda.get_device_name(0))  # 输出GPU设备名称
NVIDIA GeForce RTX 5090 D
>>>

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this issue has already been resolved. The GPU detection logic has been fixed and is now working properly. You can install it using the cu128 setup.
