### ISSUE TITLE
[Guide/Fix] RTX 5090 / 50-Series Support - Installation Steps

### ISSUE THREAD

**Issue by Astroburner** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2745]
**RVC WebUI & Realtime GUI - RTX 50-Series (Blackwell) Installation Guide**
This guide provides a working installation method for NVIDIA RTX 5090 / 5080 (Blackwell Architecture) users. Standard installation scripts will fail because they lack the necessary CUDA 12.8 / PyTorch Nightly kernels required for the new architecture.

Tested Environment:

GPU: RTX 5090
OS: Windows 11
Date: January 2026
🛠️ Prerequisites
Anaconda / Miniconda: [Download here](https://docs.anaconda.com/miniconda/) (Essential for environment management).
Git: [Download here](https://git-scm.com/downloads).
VS Build Tools: Ensure you have C++ build tools installed (needed for compiling Fairseq).

**📦 Step 1: Environment Setup**
Open Anaconda Prompt (or PowerShell with Conda) and execute **as administrator**:

Copy# 1. Create a clean Python 3.10 environment
conda create -n rvc_5090 python=3.10 -y
conda activate rvc_5090

# 2. Install FFmpeg and Git via Conda (avoids PATH issues)
conda install -c conda-forge ffmpeg git -y

# 3. Clone the Repository
git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
cd Retrieval-based-Voice-Conversion-WebUI

**🔥 Step 2: Installing PyTorch for Blackwell (Critical)**
The RTX 50-series requires CUDA 12.8+ (or latest Nightly) support. Do NOT install the standard torch version from requirements.txt.

Copy# Install PyTorch Nightly with CUDA 12.8 support
pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

⚙️ Step 3: Dependencies & Fixes
We need to modify requirements to prevent conflicts and compile fairseq manually.

Edit requirements.txt: Open the file and remove/comment out the following lines:

torch==...
torchvision==...
torchaudio==...
fairseq==...
gradio==...
numpy==...

Install Dependencies manually (Admin rights might be required for Fairseq): Note: If you get a "metadata" error, downgrade pip first: python -m pip install "pip<24.1"

Copy# 1. Install Numpy & Numba compatible versions
pip install numba numpy==1.23.5

# 2. Install OmegaConf (required for Fairseq)
pip install omegaconf==2.0.6

# 3. Compile Fairseq from Source (Fixes metadata/version errors)
pip install git+https://github.com/facebookresearch/fairseq.git

# 4. Install Gradio & Audio tools
pip install gradio==3.41.2 torchcrepe

# 5. Install remaining requirements
pip install -r requirements.txt

# 6. Fix Tensorboard
pip uninstall tb-nightly tensorboard -y
pip install tensorboard

**📥 Step 4: Minimal Model Download**
Don't download the full 50GB repo. Use this Python script to download only what you need for V2 training and inference.

Create a file named smart_download.py in the RVC folder and paste this code:

Copyfrom huggingface_hub import hf_hub_download
import os

files = [
    "hubert_base.pt", "rmvpe.pt", "rmvpe.onnx",
    "pretrained_v2/f0D40k.pth", "pretrained_v2/f0G40k.pth",
    "pretrained_v2/f0D48k.pth", "pretrained_v2/f0G48k.pth",
    "uvr5_weights/HP2_all_vocals.pth", "uvr5_weights/VR-DeEchoNormal.pth"
]

for f in files:
    print(f"Downloading {f}...")
    os.makedirs(os.path.dirname(f) if os.path.dirname(f) else ".", exist_ok=True)
    hf_hub_download(repo_id="lj1995/VoiceConversionWebUI", filename=f, local_dir=".", local_dir_use_symlinks=False)
print("Done.")
Run it:

Copypython smart_download.py

**🚀 Step 5: Running the WebUI (Training/Inference)**
Simply run:

Copypython infer-web.py
Check Console: Ensure it says Found GPU NVIDIA GeForce RTX 5090.
Note: You might see UserWarning: NVIDIA GeForce RTX 5090... is not compatible. Ignore this. As long as you installed the Nightly PyTorch in Step 2, it will work via JIT compilation.
🎤 Step 6: Running Realtime Voice Changer (GUI)
The Realtime GUI (gui_v1.py) requires a specific startup script to ensure it finds the correct environment.

Create a file named start_realtime.bat in the RVC folder.
Paste the following (Adjust CONDA_ROOT if you installed Anaconda elsewhere):
@echo off
setlocal

REM Adjust this path to your Conda installation
set CONDA_ROOT=C:\ProgramData\miniconda3

call "%CONDA_ROOT%\Scripts\activate.bat" rvc_5090

REM Ensures PyTorch sees the device correctly
set CUDA_VISIBLE_DEVICES=0

echo Starting RVC Realtime GUI on RTX 50-Series...
python gui_v1.py

pause
Run start_realtime.bat.
⚡ Optimal Realtime Settings for RTX 5090
To get near-zero latency ( < 50ms ):

Audio Device: Select Windows DirectSound or WASAPI (Do not use MME).
Sample Length: Drag this Left (0.05 - 0.10). Lower is faster.
Extra Inference Time: Set to 0.5 or lower.
Pitch Detection: Use rmvpe (Best quality) or fcpe (Fastest).
Index Rate: ~0.7 (If you have an index file).
❓ Troubleshooting
Error: no kernel image is available for execution: This means your PyTorch version is too old for the 5090. Repeat Step 2 and force-install cu128 (Nightly).
Error: module 'faiss' has no attribute...: Ignore the AVX2 warning in the console. As long as it says "Successfully loaded faiss", it works.
High Latency: Ensure you are NOT using MME audio drivers. Reduce "Sample Length" in the GUI until audio crackles, then increase slightly.

**Comment by myKiraa** [comment]
Привет, друг! А ты можешь помочь - предоставить готовый файл Zip, для скачивания? Я очень плохо разбираюсь в пк :(

**Comment by myKiraa** [comment]
Или записать видео с инструкцией

**Comment by myKiraa** [comment]
Hey, friend! Can you help me by providing a ready-made Zip file for download? I'm really bad with PCs :(

**Comment by BluePeacocks** [comment]
I own an RTX 5070, would love seeing how you run it with a video

**Comment by Ghoul1538** [comment]
Can confirm, just follow the steps here and it works. :D Ty
