### ISSUE TITLE
3090 GPU not recognised

### ISSUE THREAD

**Issue by Saganaki22** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#350]
I cant get 3090 to be recognised by the script

running on windows with virtual enviroment and all requirements are already satisfied

using python 3.10

cuda toolkit is installed

deleted virtual enviroment and files and reinstalled but get the same error

i'm out of ideas, please help!

(myenv) H:\RVC-beta>python infer-web.py
Use Language: en_US
没有发现支持的N卡, 使用CPU进行推理
Running on local URL:  http://0.0.0.0:7865

**Comment by Saganaki22** [comment]
It seems i have fixed it.

i ran this command to show what torch version it was using

`python -c "import torch; print(torch.__version__)"`

and it seems it was defaulting on Pytorch for CPU. 
So then i updated pip, reinstalled nvidia drivers, python, created a new venv, reinstalled requirements txt, 

Ran this command to make sure i request torch for CUDA not CPU:

`pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117`

 restarted pc

✅ Fixed

**Comment by Mejnun333** [comment]
Thank you so much! WORK for Meeee!
