### ISSUE TITLE
 CUDA out of memory.

### ISSUE THREAD

**Issue by ANRTNT** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#453]
What should I do to this problem?

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by RVC-Boss** [comment]
try batch size 1

**Comment by luckyClover233** [comment]
> try batch size 1
我使用5月版，推理的时候报错提示跟这个类似（使用同版本所训练的音色模型）。不过我原来的4月版本没报过错。看楼上说更新显卡驱动就好了。但是我电脑里的驱动都已经是最新的了。所以不知道要怎么处理了。
Tried to allocate 418.00 MiB
 (GPU 0; 6.00 GiB total capacity; 
 3.01 GiB already allocated;
 363.12 MiB free; 
 3.82 GiB reserved in total by PyTorch) If reserved memory is >>
allocated memory try setting max_split_size_mb to avoid fragmentation.
See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
