### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. 

### ISSUE THREAD

**Issue by linuxkerem** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#654]
I'm always getting this error even I downed my settings to the bottom:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/88890068/f8f8110f-c89a-445a-962b-a29da5c3e085)

Here is my settings:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/88890068/0b401472-274a-4931-b3ae-3fb3c12e5ff7)

**Comment by RVC-Boss** [comment]
What's your GPU?

**Comment by linuxkerem** [comment]
> What's your GPU?

NVIDIA GeForce RTX 3050 Laptop GPU

**Comment by MazenVR** [comment]
You need GPU >= 8GB

**Comment by krzysiek546** [comment]
Are all of your samples below 10 seconds? Try trimm them and try again run training.

**Comment by DrangerH** [comment]
I have exactly the same problem, same GPU. I tried reducing the batch size to 1 and using >10s audio samples, it didn't work.

**Comment by qing762** [comment]
Same problem. I tried running on two different pc. One with Asus NVIDIA GeForce RTX 2080 (6GB) and one with Colorful NVIDIA GeForce RTX 3060 (4GB). Both having the same problem.

**Comment by krzysiek546** [comment]
> Same problem. I tried running on two different pc. One with Asus NVIDIA GeForce RTX 2080 (6GB) and one with Colorful NVIDIA GeForce RTX 3060 (4GB). Both having the same problem.

In my case doing all things on Ubuntu 22.04 resolved all OOM errors. Unfortunately apparently Windows have some problems with allocating VRAM. You should start training with batch=1 on 4GB VRAM easily. I train without any problems on GTX 1660 Super 6GB with batch=3.

**Comment by linuxkerem** [comment]
> > Same problem. I tried running on two different pc. One with Asus NVIDIA GeForce RTX 2080 (6GB) and one with Colorful NVIDIA GeForce RTX 3060 (4GB). Both having the same problem.
> 
> In my case doing all things on Ubuntu 22.04 resolved all OOM errors. Unfortunately apparently Windows have some problems with allocating VRAM. You should start training with batch=1 on 4GB VRAM easily. I train without any problems on GTX 1660 Super 6GB with batch=3.

Yes, I also think the problem is Windows related. I'll try with Fedora tomorrow and report back

**Comment by Srinath320** [comment]
If it's windows related issue, is there any walkaround found for this? I'm also facing the same problem. Though v1 runs perfectly fine on my system.

**Comment by SaafirHale** [comment]
I'm having the same issues. I have a GeForce RTX 3050 with 4GB. I can run stable diffusion and deforum locally. I would really love to be able to run it.

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)#q8cuda-errorcuda-out-of-memory

**Comment by DYNOs1rX762** [comment]
> I'm always getting this error even I downed my settings to the bottom:
> 
> ![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/88890068/f8f8110f-c89a-445a-962b-a29da5c3e085)
> 
> 
> Here is my settings:
> 
> ![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/88890068/0b401472-274a-4931-b3ae-3fb3c12e5ff7)
> 

Did you find a solution

**Comment by desplus** [comment]
I I also had this problem before on my 4GB graphics card

I set the following options and the problem was solved, of course you can increase the values, I set the minimum for testing and the problem was solved
My graphics card is "NVIDIA GeForce GTX 1650 with Max-Q Design"

rmvpe
Save frequency = 1
Batch size per GPU = 1
Cache all training sets to GPU = no
