### ISSUE TITLE
Voice changing issue (CUDA out of memory)

### ISSUE THREAD

**Issue by EnderRL** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#687]
Hi I am new to RVC, and I have little knowledge about it.

I was trying out how powerful the application, and it was really cool. I was able to separate the voice and instrumental.
But when it comes to **changing voice**, I getting these error:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/121793770/8b3e3038-5168-4efb-941f-3a232e75c116)
I assume that because my gpu **ran out of memory**:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/121793770/29036aff-552b-419a-aff6-a6d1cdda0426)
I was using a random trained voice (the .pth file) from this [repo](https://huggingface.co/analogspiderweb/analogspiderweb_RVC/blob/main/villager.zip) 
And I sure it wasn’t the problem (I haven’t try the other voice yet), and it was because of my gpu limitations. I also haven’t try train a voice yet but I assume that it will also give out of memory error.

So my question is:
1. Can I solve the out of memory issue? Was it related to the “[config.py](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/config.py)”? Because I did read the [faq](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)#q8cuda-errorcuda-out-of-memory) and I think I need to change some settings in the file. 
2. If not, can I use cpu processing for the voice changer? I am fine with the slow processing speed as long as it came with results!

Pc specs:
Cpu: Core i3 gen 12th (4 core 8 threads)
Ram: 16GB
Gpu: GTX 950 (2GB vram)

I also forgot to mention that I used the installation script from this [video](https://youtu.be/Y8IxVVQBEpc) (or the powershell iex script: `iex (irm rvc.tc.ht)`) so that I saved my time installing manually. 

Thanks!

哈咯哈咯，我的华文会很差，只是希望可以让你们明白点。
我刚接触这个变音器，所以我不是很会用。

我只是来看看这个东西有多好玩，就觉得这个分唱歌的和伴奏的很成功。
但是到变音的时候，就开始有问题。我是觉得因为out of memory的问题，所以就求方法搞这个问题。

1. 所以我想问的是请问那个out of memory的问题可以解决吗？是不是关系到“config.py”？
2. 如果不能的话我可以用CPU操作吗？

我电脑的配件:
Cpu: intel core i3 gen 12th
Ram: 16GB
Gpu: GTX 950 (2GB vram)

謝謝!

**Comment by EnderRL** [comment]
Update: nevermind, in the "[config.py](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/config.py)", just lower the `x_pad, x_query, x_center, x_max`
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/121793770/e4857a8d-43d0-45f6-b0bd-1956cd0ee4a9)
so it won't show cuda timeout, and the problem is not even related to gpu vram, it was fine.
Let me know if i can actually improve this, otherwise problem solved! Thanks!

**Comment by ms903x1** [comment]
gtx950 is not within the supported range. Please use a Niadiv graphics card of gtx10xx series or higher

**Comment by RVC-Boss** [comment]
2G GPU memory is not enough for inference.
If you want to use CPU to inference,  you can modify this line
self.device = "cuda:xxx"
to 
self.device = "cpu"

**Comment by EnderRL** [comment]
> 

Thanks! It works very stable for now.
